import { Config } from "effect"

function truthy(...keys: string[]) {
  for (const key of keys) {
    const value = process.env[key]?.toLowerCase()
    if (value === "true" || value === "1") return true
  }
  return false
}

function number(...keys: string[]) {
  for (const key of keys) {
    const value = process.env[key]
    if (!value) continue
    const parsed = Number(value)
    if (Number.isInteger(parsed) && parsed > 0) return parsed
  }
  return undefined
}

function envVar(...keys: string[]) {
  for (const key of keys) {
    const value = process.env[key]
    if (value !== undefined) return value
  }
  return undefined
}

const OPENCODE_EXPERIMENTAL = truthy("OMNI_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
const OPENCODE_DISABLE_CLAUDE_CODE = truthy("OMNI_DISABLE_CLAUDE_CODE", "OPENCODE_DISABLE_CLAUDE_CODE")
const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
  OPENCODE_DISABLE_CLAUDE_CODE || truthy("OMNI_DISABLE_CLAUDE_CODE_SKILLS", "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["OMNI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"] ?? process.env["OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCODE_AUTO_SHARE: truthy("OMNI_AUTO_SHARE", "OPENCODE_AUTO_SHARE"),
  OPENCODE_AUTO_HEAP_SNAPSHOT: truthy("OMNI_AUTO_HEAP_SNAPSHOT", "OPENCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: envVar("OMNI_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH"),
  OPENCODE_CONFIG: envVar("OMNI_CONFIG", "OPENCODE_CONFIG"),
  OPENCODE_CONFIG_CONTENT: envVar("OMNI_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT"),
  OPENCODE_DISABLE_AUTOUPDATE: truthy("OMNI_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthy("OMNI_ALWAYS_NOTIFY_UPDATE", "OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthy("OMNI_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthy("OMNI_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthy("OMNI_SHOW_TTFD", "OPENCODE_SHOW_TTFD"),
  OPENCODE_PERMISSION: envVar("OMNI_PERMISSION", "OPENCODE_PERMISSION"),
  OPENCODE_DISABLE_DEFAULT_PLUGINS: truthy("OMNI_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS"),
  OPENCODE_DISABLE_LSP_DOWNLOAD: truthy("OMNI_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD"),
  OPENCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("OMNI_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthy("OMNI_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthy("OMNI_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthy("OMNI_DISABLE_MOUSE", "OPENCODE_DISABLE_MOUSE"),
  OPENCODE_DISABLE_CLAUDE_CODE,
  OPENCODE_DISABLE_CLAUDE_CODE_PROMPT: OPENCODE_DISABLE_CLAUDE_CODE || truthy("OMNI_DISABLE_CLAUDE_CODE_PROMPT", "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  OPENCODE_DISABLE_CLAUDE_CODE_SKILLS,
  OPENCODE_DISABLE_EXTERNAL_SKILLS: truthy("OMNI_DISABLE_EXTERNAL_SKILLS", "OPENCODE_DISABLE_EXTERNAL_SKILLS"),
  OPENCODE_FAKE_VCS: envVar("OMNI_FAKE_VCS", "OPENCODE_FAKE_VCS"),
  OPENCODE_SERVER_PASSWORD: envVar("OMNI_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD"),
  OPENCODE_SERVER_USERNAME: envVar("OMNI_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME"),
  OPENCODE_ENABLE_QUESTION_TOOL: truthy("OMNI_ENABLE_QUESTION_TOOL", "OPENCODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  OPENCODE_EXPERIMENTAL,
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_ICON_DISCOVERY: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OMNI_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_ENABLE_EXA: truthy("OMNI_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA"),
  OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("OMNI_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OMNI_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OPENCODE_EXPERIMENTAL_OXFMT: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT"),
  OPENCODE_EXPERIMENTAL_LSP_TY: truthy("OMNI_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY"),
  OPENCODE_EXPERIMENTAL_LSP_TOOL: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL"),
  OPENCODE_EXPERIMENTAL_PLAN_MODE: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE"),
  OPENCODE_EXPERIMENTAL_SCOUT: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_SCOUT", "OPENCODE_EXPERIMENTAL_SCOUT"),
  OPENCODE_ENABLE_PARALLEL: truthy("OMNI_ENABLE_PARALLEL", "OPENCODE_ENABLE_PARALLEL") || truthy("OMNI_EXPERIMENTAL_PARALLEL", "OPENCODE_EXPERIMENTAL_PARALLEL"),
  OPENCODE_MODELS_URL: envVar("OMNI_MODELS_URL", "OPENCODE_MODELS_URL"),
  OPENCODE_MODELS_PATH: envVar("OMNI_MODELS_PATH", "OPENCODE_MODELS_PATH"),
  OPENCODE_DISABLE_EMBEDDED_WEB_UI: truthy("OMNI_DISABLE_EMBEDDED_WEB_UI", "OPENCODE_DISABLE_EMBEDDED_WEB_UI"),
  OPENCODE_DB: envVar("OMNI_DB", "OPENCODE_DB"),
  OPENCODE_DISABLE_CHANNEL_DB: truthy("OMNI_DISABLE_CHANNEL_DB", "OPENCODE_DISABLE_CHANNEL_DB"),
  OPENCODE_SKIP_MIGRATIONS: truthy("OMNI_SKIP_MIGRATIONS", "OPENCODE_SKIP_MIGRATIONS"),
  OPENCODE_STRICT_CONFIG_DEPS: truthy("OMNI_STRICT_CONFIG_DEPS", "OPENCODE_STRICT_CONFIG_DEPS"),

  OPENCODE_WORKSPACE_ID: envVar("OMNI_WORKSPACE_ID", "OPENCODE_WORKSPACE_ID"),
  OPENCODE_EXPERIMENTAL_WORKSPACES: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES"),
  OPENCODE_EXPERIMENTAL_EVENT_SYSTEM: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_EVENT_SYSTEM", "OPENCODE_EXPERIMENTAL_EVENT_SYSTEM"),
  OPENCODE_EXPERIMENTAL_SESSION_SWITCHING: OPENCODE_EXPERIMENTAL || truthy("OMNI_EXPERIMENTAL_SESSION_SWITCHING", "OPENCODE_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("OMNI_DISABLE_PROJECT_CONFIG", "OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_TUI_CONFIG() {
    return envVar("OMNI_TUI_CONFIG", "OPENCODE_TUI_CONFIG")
  },
  get OPENCODE_CONFIG_DIR() {
    return envVar("OMNI_CONFIG_DIR", "OPENCODE_CONFIG_DIR")
  },
  get OPENCODE_PURE() {
    return truthy("OMNI_PURE", "OPENCODE_PURE")
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return envVar("OMNI_PLUGIN_META_FILE", "OPENCODE_PLUGIN_META_FILE")
  },
  get OPENCODE_CLIENT() {
    return envVar("OMNI_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  },
}
